# Generated by Django 4.2.8 on 2026-03-15 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("legal", "0004_fix_legacy_schema"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="UTC timestamp when the event was recorded."
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True,
                        help_text='Python class name of the entity (e.g. "Patient", "Appointment").',
                        max_length=100,
                    ),
                ),
                (
                    "entity_id",
                    models.UUIDField(
                        db_index=True, help_text="PK of the entity that triggered the event."
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("PATIENT_CREATED", "Patient Created"),
                            ("PATIENT_UPDATED", "Patient Updated"),
                            ("PATIENT_SOFT_DELETED", "Patient Soft-Deleted"),
                            ("APPOINTMENT_CREATED", "Appointment Created"),
                            ("APPOINTMENT_UPDATED", "Appointment Updated"),
                            ("APPOINTMENT_CANCELLED", "Appointment Cancelled"),
                            ("APPOINTMENT_NO_SHOW", "Appointment No-Show"),
                            ("APPOINTMENT_CHECKED_IN", "Appointment Checked-In"),
                            ("ENCOUNTER_CREATED", "Encounter Created"),
                            ("ENCOUNTER_FINALIZED", "Encounter Finalized"),
                            ("ENCOUNTER_CANCELLED", "Encounter Cancelled"),
                            ("CONSENT_SIGNED", "Consent Signed"),
                            ("CLINICAL_PHOTO_UPLOADED", "Clinical Photo Uploaded"),
                            ("PROPOSAL_CREATED", "Proposal Created"),
                            ("PROPOSAL_SENT", "Proposal Sent"),
                            ("PROPOSAL_ACCEPTED", "Proposal Accepted"),
                            ("PROPOSAL_CANCELLED", "Proposal Cancelled"),
                            ("SALE_CREATED", "Sale Created"),
                            ("REFUND_CREATED", "Refund Created"),
                            ("TREATMENT_SESSION_COMPLETED", "Treatment Session Completed"),
                        ],
                        db_index=True,
                        help_text="Semantic event name from AuditEventType.",
                        max_length=60,
                    ),
                ),
                (
                    "payload_json",
                    models.JSONField(
                        default=dict, help_text="Arbitrary JSON payload — must be serialisable."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Alias for timestamp (same value)."
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        help_text="Owning legal entity — required for tenant isolation.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="legal.legalentity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the event (null for system/Celery actions).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "ops_audit_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["timestamp"], name="idx_auditlog_timestamp"),
                    models.Index(fields=["legal_entity"], name="idx_auditlog_le"),
                    models.Index(fields=["entity_type"], name="idx_auditlog_entity_type"),
                    models.Index(fields=["entity_id"], name="idx_auditlog_entity_id"),
                    models.Index(fields=["event_type"], name="idx_auditlog_event_type"),
                ],
            },
        ),
    ]
