# Generated by Django 4.2.8 on 2026-03-15 22:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clinical", "0114_appointmenttype_and_more"),
        ("legal", "0004_fix_legacy_schema"),
        ("core", "0002_cliniclocation_tenant"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ClinicLocation",
            new_name="Clinic",
        ),
        migrations.AlterModelOptions(
            name="clinic",
            options={"verbose_name": "Clinic", "verbose_name_plural": "Clinics"},
        ),
    ]
