# Generated by Django 4.2.8 on 2025-12-16 20:35

import apps.photos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clinical", "0007_add_medical_fields_to_patient"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkinPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.photos.models.photo_upload_path, verbose_name="Image"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="thumbnails/", verbose_name="Thumbnail"
                    ),
                ),
                (
                    "body_part",
                    models.CharField(
                        choices=[
                            ("face", "Face"),
                            ("scalp", "Scalp"),
                            ("neck", "Neck"),
                            ("chest", "Chest"),
                            ("back", "Back"),
                            ("arms", "Arms"),
                            ("hands", "Hands"),
                            ("legs", "Legs"),
                            ("feet", "Feet"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Body Part",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags",
                        max_length=500,
                        verbose_name="Tags",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("taken_at", models.DateTimeField(auto_now_add=True, verbose_name="Taken At")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "thumbnail_generated",
                    models.BooleanField(default=False, verbose_name="Thumbnail Generated"),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos",
                        to="clinical.encounter",  # Changed from encounters to clinical
                        verbose_name="Encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legacy_photos",
                        to="clinical.patient",
                        verbose_name="Patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skin Photo",
                "verbose_name_plural": "Skin Photos",
                "db_table": "skin_photos",
                "ordering": ["-taken_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "-taken_at"], name="skin_photos_patient_5dd8ea_idx"
                    ),
                    models.Index(fields=["encounter"], name="skin_photos_encount_43cfa4_idx"),
                    models.Index(fields=["body_part"], name="skin_photos_body_pa_fc727d_idx"),
                ],
            },
        ),
    ]
