# Generated by Django 4.2.8 on 2025-12-30 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clinical", "0101_encounter_attachment_counters"),
        ("photos", "0002_update_encounter_fk_to_clinical"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skinphoto",
            name="encounter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_photos_link",
                to="clinical.encounter",
                verbose_name="Encounter",
            ),
        ),
    ]
