# Generated by Django 4.2.8 on 2026-02-23 23:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authz", "0007_system_plane_legal_entity"),
        ("sales", "0007_sale_legal_entity"),
        ("proposals", "0004_initial"),
        ("clinical", "0103_move_proposals_to_own_app"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreatmentPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "package_name",
                    models.CharField(
                        help_text="Treatment name snapshot from proposal line", max_length=255
                    ),
                ),
                (
                    "description_snapshot",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Treatment description snapshot from proposal line",
                    ),
                ),
                (
                    "planned_sessions",
                    models.PositiveIntegerField(
                        help_text="Total number of sessions in the package"
                    ),
                ),
                (
                    "completed_sessions",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of sessions completed so far"
                    ),
                ),
                (
                    "total_price_snapshot",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total price snapshot from proposal line (line_total)",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR",
                        help_text="Currency code (snapshot from proposal)",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        help_text="Current lifecycle status",
                        max_length=20,
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the plan was activated (first appointment created)",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When all planned sessions were completed", null=True
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, help_text="When the plan was cancelled", null=True
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(
                        blank=True, default="", help_text="Reason for cancellation (if applicable)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient receiving the treatment plan",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="treatment_plans",
                        to="clinical.patient",
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assigned practitioner (may differ per appointment)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treatment_plans",
                        to="authz.practitioner",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        help_text="Source proposal that generated this plan",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="treatment_plans",
                        to="proposals.proposal",
                    ),
                ),
                (
                    "proposal_line",
                    models.OneToOneField(
                        help_text="Specific proposal line (full_package) that originated this plan",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="treatment_plan",
                        to="proposals.proposalline",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sale generated alongside this plan",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treatment_plans",
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Treatment Plan",
                "verbose_name_plural": "Treatment Plans",
                "db_table": "treatment_plan",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["patient"], name="idx_tp_patient"),
                    models.Index(fields=["proposal"], name="idx_tp_proposal"),
                    models.Index(fields=["status"], name="idx_tp_status"),
                    models.Index(fields=["practitioner"], name="idx_tp_practitioner"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="treatmentplan",
            constraint=models.CheckConstraint(
                check=models.Q(("planned_sessions__gt", 0)), name="tp_planned_sessions_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="treatmentplan",
            constraint=models.CheckConstraint(
                check=models.Q(("completed_sessions__gte", 0)),
                name="tp_completed_sessions_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="treatmentplan",
            constraint=models.CheckConstraint(
                check=models.Q(("total_price_snapshot__gte", 0)), name="tp_total_price_non_negative"
            ),
        ),
    ]
