# Generated by Django 4.2.8 on 2026-02-24 23:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("authz", "0007_system_plane_legal_entity"),
        ("clinical", "0105_patient_insurance"),
        ("treatment_plans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreatmentSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        help_text="Current lifecycle status",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Brief session notes (editable in draft only)",
                    ),
                ),
                (
                    "performed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the session was performed (auto-set on complete if null)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        help_text="Source appointment (1:1 — unique constraint)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="treatment_session",
                        to="clinical.appointment",
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Practitioner who performed the session",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treatment_sessions",
                        to="authz.practitioner",
                    ),
                ),
                (
                    "treatment_plan",
                    models.ForeignKey(
                        help_text="Parent treatment plan",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="treatment_plans.treatmentplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Treatment Session",
                "verbose_name_plural": "Treatment Sessions",
                "db_table": "treatment_session",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["treatment_plan"], name="idx_ts_treatment_plan"),
                    models.Index(fields=["status"], name="idx_ts_status"),
                    models.Index(fields=["practitioner"], name="idx_ts_practitioner"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="treatmentsession",
            constraint=models.CheckConstraint(
                check=models.Q(("status__in", ["draft", "completed", "cancelled"])),
                name="ts_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="treatmentsession",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("status__in", ["draft", "cancelled"]),
                    ("performed_at__isnull", False),
                    _connector="OR",
                ),
                name="ts_performed_at_required_when_completed",
            ),
        ),
    ]
