# Generated by Django 4.2.8 on 2026-03-09 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("legal", "0004_fix_legacy_schema"),
        ("treatment_plans", "0004_v3_patch"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentsession",
            name="legal_entity",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning legal entity (tenant isolation).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                to="legal.legalentity",
            ),
        ),
    ]
