# Generated by Django 4.2.8 on 2025-12-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authz", "0002_bootstrap_reception_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="practitioner",
            name="role_type",
            field=models.CharField(
                choices=[
                    ("practitioner", "Practitioner"),
                    ("assistant", "Assistant"),
                    ("clinical_manager", "Clinical Manager"),
                ],
                default="practitioner",
                help_text="Type of clinical role (practitioner, assistant, clinical_manager)",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="practitioner",
            index=models.Index(fields=["role_type"], name="idx_practitioner_role"),
        ),
    ]
