# Generated by Django 4.2.8 on 2025-12-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0003_practitioner_role_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='calendly_url',
            field=models.URLField(blank=True, help_text='Personal Calendly scheduling URL for this practitioner. If null, system uses CALENDLY_DEFAULT_URL from settings.', max_length=500, null=True),
        ),
    ]
