# Generated by Django 4.2.8 on 2025-12-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authz", "0004_add_calendly_url_to_practitioner"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, help_text="First name of the user", max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, help_text="Last name of the user", max_length=150),
        ),
    ]
