# Generated by Django 4.2.8 on 2025-12-27 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0005_add_user_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='If true, user must change password on next login'),
        ),
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('create_user', 'Create User'), ('update_user', 'Update User'), ('reset_password', 'Reset Password'), ('change_password', 'Change Password'), ('deactivate_user', 'Deactivate User'), ('activate_user', 'Activate User')], max_length=20)),
                ('metadata', models.JSONField(default=dict, help_text='Changed fields, before/after values, IP address, user agent, etc.')),
                ('actor_user', models.ForeignKey(help_text='Admin user who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(help_text='User who was affected by the action', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Audit Log',
                'verbose_name_plural': 'User Audit Logs',
                'db_table': 'user_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='idx_user_audit_created'), models.Index(fields=['actor_user'], name='idx_user_audit_actor'), models.Index(fields=['target_user'], name='idx_user_audit_target'), models.Index(fields=['action'], name='idx_user_audit_action')],
            },
        ),
    ]
