# Generated by Django 4.2.8 on 2026-02-22 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("legal", "0003_system_plane_legal_entity"),
        ("authz", "0006_add_must_change_password_and_audit"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="legal_entity",
            field=models.ForeignKey(
                blank=True,
                help_text="Legal entity this user belongs to. NULL for superusers.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="legal.legalentity",
            ),
        ),
    ]
