# Generated by Django 4.2.8 on 2026-03-15 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authz", "0009_drop_calendly_event_type_uris"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="practitioner",
            name="calendly_url",
        ),
    ]
