"""
Layer 2 A2: Sales Domain Integrity

This migration:
1. Creates Sale and SaleLine models
2. Adds check constraints (quantity>0, unit_price>=0, totals>=0)
3. Adds performance indexes
4. Cleans any existing invalid sales data (if migrating from placeholder)

Business Rules Enforced:
- SaleLine.quantity > 0
- SaleLine.unit_price >= 0
- SaleLine.discount >= 0
- SaleLine.line_total >= 0
- Sale.subtotal >= 0
- Sale.tax >= 0
- Sale.discount >= 0
- Sale.total >= 0
- Sale totals must be consistent

Generated by Django 4.2.8 on 2025-12-15
"""
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


def clean_invalid_sales(apps, schema_editor):
    """
    Clean sales with invalid data before adding constraints.
    
    Actions:
    1. Fix negative totals -> set to 0
    2. Mark sales with inconsistent data as cancelled
    3. Log all corrections to ClinicalAuditLog
    """
    Sale = apps.get_model('sales', 'Sale')
    ClinicalAuditLog = apps.get_model('clinical', 'ClinicalAuditLog')
    
    corrections = []
    
    # Fix sales with negative totals
    invalid_sales = Sale.objects.filter(
        models.Q(total__lt=0) | models.Q(subtotal__lt=0) |
        models.Q(tax__lt=0) | models.Q(discount__lt=0)
    )
    
    for sale in invalid_sales:
        old_values = {
            'total': sale.total,
            'subtotal': sale.subtotal,
            'tax': sale.tax,
            'discount': sale.discount,
            'status': sale.status,
        }
        
        # Fix negative values
        if sale.total < 0:
            sale.total = Decimal('0.00')
        if sale.subtotal < 0:
            sale.subtotal = Decimal('0.00')
        if sale.tax < 0:
            sale.tax = Decimal('0.00')
        if sale.discount < 0:
            sale.discount = Decimal('0.00')
        
        # Mark as cancelled if it was in a problematic state
        if sale.status not in ['cancelled', 'refunded']:
            sale.status = 'cancelled'
            sale.cancellation_reason = 'Auto-cancelled during Layer 2 A2 migration: invalid financial values'
        
        sale.save()
        
        corrections.append({
            'sale_id': str(sale.id),
            'old_values': old_values,
            'action': 'fixed_negative_values_and_cancelled',
        })
        
        # Log to audit
        try:
            ClinicalAuditLog.objects.create(
                entity_type='sale',
                entity_id=str(sale.id),
                action='data_migration_correction',
                user_id=None,
                snapshot={'old': old_values, 'correction': 'Layer 2 A2 migration: fixed negative values'},
                ip_address='127.0.0.1',
                user_agent='Django Migration 0002_layer2_a2_sales_integrity',
            )
        except Exception:
            # ClinicalAuditLog might not exist in test environments
            pass
    
    print(f"Layer 2 A2 Migration: Corrected {len(corrections)} invalid sales")
    if corrections:
        print("Corrections:")
        for c in corrections[:10]:  # Show first 10
            print(f"  - Sale {c['sale_id']}: {c['action']}")


def clean_sale_appointment_patient_coherence(apps, schema_editor):
    """
    Clean sales where appointment.patient != sale.patient.
    
    Action: Set appointment=NULL for mismatches
    """
    Sale = apps.get_model('sales', 'Sale')
    ClinicalAuditLog = apps.get_model('clinical', 'ClinicalAuditLog')
    
    corrections = []
    
    # Find sales with appointment-patient mismatch
    mismatched_sales = Sale.objects.filter(
        appointment__isnull=False,
        patient__isnull=False
    ).select_related('appointment', 'patient')
    
    for sale in mismatched_sales:
        if sale.appointment and sale.patient:
            if sale.appointment.patient_id != sale.patient_id:
                old_appointment_id = sale.appointment_id
                sale.appointment = None
                sale.save()
                
                corrections.append({
                    'sale_id': str(sale.id),
                    'old_appointment_id': str(old_appointment_id),
                    'patient_id': str(sale.patient_id),
                    'action': 'appointment_cleared_due_to_patient_mismatch',
                })
                
                # Log to audit
                try:
                    ClinicalAuditLog.objects.create(
                        entity_type='sale',
                        entity_id=str(sale.id),
                        action='data_migration_correction',
                        user_id=None,
                        snapshot={
                            'correction': 'Layer 2 A2: cleared appointment due to patient mismatch',
                            'old_appointment_id': str(old_appointment_id),
                        },
                        ip_address='127.0.0.1',
                        user_agent='Django Migration 0002_layer2_a2_sales_integrity',
                    )
                except Exception:
                    pass
    
    print(f"Layer 2 A2 Migration: Cleared {len(corrections)} appointment mismatches")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '__first__'),
        ('clinical', '0005_fix_clinicalphoto_index_name'),
    ]

    operations = [
        # Step 1: Create models
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_number', models.CharField(blank=True, help_text='Human-readable sale number (e.g., INV-2025-001)', max_length=50, null=True, unique=True, verbose_name='Sale Number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='draft', max_length=20, verbose_name='Status')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of line totals before tax and discounts', max_digits=10, verbose_name='Subtotal')),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Tax')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Discount')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final total (subtotal + tax - discount)', max_digits=10, verbose_name='Total')),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code', max_length=3, verbose_name='Currency')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='Cancellation Reason')),
                ('refund_reason', models.TextField(blank=True, null=True, verbose_name='Refund Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('appointment', models.ForeignKey(blank=True, help_text='Optional appointment this sale is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='clinical.appointment', verbose_name='Appointment')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'db_table': 'sales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255, verbose_name='Product/Service')),
                ('product_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Must be greater than 0', max_digits=10, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit (must be >= 0)', max_digits=10, verbose_name='Unit Price')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line-level discount (must be >= 0)', max_digits=10, verbose_name='Discount')),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Calculated as quantity * unit_price - discount', max_digits=10, verbose_name='Line Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.sale', verbose_name='Sale')),
            ],
            options={
                'verbose_name': 'Sale Line',
                'verbose_name_plural': 'Sale Lines',
                'db_table': 'sale_lines',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['sale'], name='idx_sale_line_sale')],
            },
        ),
        
        # Step 2: Clean invalid data BEFORE adding constraints
        migrations.RunPython(
            clean_invalid_sales,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            clean_sale_appointment_patient_coherence,
            reverse_code=migrations.RunPython.noop,
        ),
        
        # Step 3: Add constraints (will fail if data is still invalid)
        migrations.AddConstraint(
            model_name='saleline',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='sale_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='saleline',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gte', 0)), name='sale_line_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='saleline',
            constraint=models.CheckConstraint(check=models.Q(('discount__gte', 0)), name='sale_line_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='saleline',
            constraint=models.CheckConstraint(check=models.Q(('line_total__gte', 0)), name='sale_line_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(check=models.Q(('total__gte', 0)), name='sale_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(check=models.Q(('subtotal__gte', 0)), name='sale_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(check=models.Q(('tax__gte', 0)), name='sale_tax_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(check=models.Q(('discount__gte', 0)), name='sale_discount_non_negative'),
        ),
        
        # Step 4: Add performance indexes
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['-created_at'], name='idx_sale_created'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status', '-created_at'], name='idx_sale_status_created'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['patient', '-created_at'], name='idx_sale_patient_created'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_number'], name='idx_sale_number'),
        ),
    ]
