# Generated by Django 4.2.8 on 2025-12-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0005_add_idempotency_key_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salerefund",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique key to prevent duplicate refunds for the same sale (single source of truth)",
                max_length=128,
                null=True,
                verbose_name="Idempotency Key",
            ),
        ),
    ]
