# Generated by Django 4.2.8 on 2025-12-22 (manual)

from django.db import migrations, models
import django.db.models.deletion


def assign_default_legal_entity(apps, schema_editor):
    """Assign default legal entity to all existing sales."""
    Sale = apps.get_model('sales', 'Sale')
    LegalEntity = apps.get_model('legal', 'LegalEntity')
    
    # Get the default legal entity (should exist from legal.0002)
    try:
        default_entity = LegalEntity.objects.first()
        if default_entity is None:
            # If no entity exists, create one
            default_entity = LegalEntity.objects.create(
                legal_name="Clinique (À compléter)",
                address_line_1="Adresse à compléter",
                postal_code="75001",
                city="Paris",
                country_code="FR",
                currency="EUR",
                timezone="Europe/Paris"
            )
            print(f"Created default legal entity: {default_entity.legal_name}")
        
        # Assign to all sales without legal_entity
        sales_to_update = Sale.objects.filter(legal_entity__isnull=True)
        count = sales_to_update.count()
        
        if count > 0:
            sales_to_update.update(legal_entity=default_entity)
            print(f"Assigned default legal entity to {count} sales")
        else:
            print("No sales to update (all already have legal_entity)")
            
    except Exception as e:
        print(f"Warning: Could not assign default legal entity: {e}")
        # Don't fail migration - field is nullable initially


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_create_default_entity'),
        ('sales', '0006_alter_salerefund_idempotency_key'),
    ]

    operations = [
        # Step 1: Add nullable field
        migrations.AddField(
            model_name='sale',
            name='legal_entity',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='sales',
                to='legal.legalentity',
                verbose_name='Legal entity',
                help_text='Legal entity issuing this sale (required for future invoicing compliance)'
            ),
        ),
        
        # Step 2: Assign default entity to existing sales
        migrations.RunPython(
            assign_default_legal_entity,
            reverse_code=migrations.RunPython.noop
        ),
        
        # Step 3: Make field required
        migrations.AlterField(
            model_name='sale',
            name='legal_entity',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='sales',
                to='legal.legalentity',
                verbose_name='Legal entity',
                help_text='Legal entity issuing this sale (required for future invoicing compliance)'
            ),
        ),
    ]
