# Generated by Django 4.2.8 on 2026-04-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0007_sale_legal_entity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="currency",
            field=models.CharField(
                default="EUR",
                help_text="ISO 4217 currency code",
                max_length=3,
                verbose_name="Currency",
            ),
        ),
    ]
