# Generated by Django 4.2.8 on 2025-12-22 09:26

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LegalEntity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        help_text="Official registered business name",
                        max_length=255,
                        verbose_name="Legal name (Raison sociale)",
                    ),
                ),
                (
                    "trade_name",
                    models.CharField(
                        blank=True,
                        help_text="Commercial name used for public-facing documents",
                        max_length=255,
                        verbose_name="Trade name (Nom commercial)",
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(
                        help_text="Street number and name",
                        max_length=255,
                        verbose_name="Address line 1",
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True,
                        help_text="Complement (building, floor, etc.)",
                        max_length=255,
                        verbose_name="Address line 2",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        help_text="Format: 75001 for France",
                        max_length=10,
                        verbose_name="Postal code",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "country_code",
                    models.CharField(
                        default="FR",
                        help_text="ISO 3166-1 alpha-2 code (e.g., FR, BE, CH)",
                        max_length=2,
                        verbose_name="Country code",
                    ),
                ),
                (
                    "siren",
                    models.CharField(
                        blank=True,
                        help_text="9-digit company identification number (France)",
                        max_length=9,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="SIREN must be exactly 9 digits", regex="^\\d{9}$"
                            )
                        ],
                        verbose_name="SIREN",
                    ),
                ),
                (
                    "siret",
                    models.CharField(
                        blank=True,
                        help_text="14-digit establishment identification number (France)",
                        max_length=14,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="SIRET must be exactly 14 digits", regex="^\\d{14}$"
                            )
                        ],
                        verbose_name="SIRET",
                    ),
                ),
                (
                    "vat_number",
                    models.CharField(
                        blank=True,
                        help_text="Intra-community VAT number (e.g., FR12345678901)",
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="VAT number (Numéro TVA)",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR",
                        help_text="ISO 4217 currency code (EUR, USD, etc.)",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Europe/Paris",
                        help_text="IANA timezone database name (Europe/Paris, America/New_York, etc.)",
                        max_length=50,
                        verbose_name="Timezone",
                    ),
                ),
                (
                    "invoice_footer_text",
                    models.TextField(
                        blank=True,
                        help_text="Optional text to appear at bottom of invoices (payment terms, legal notices, etc.)",
                        verbose_name="Invoice footer text",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this entity can be used for new sales/invoices",
                        verbose_name="Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Legal entity",
                "verbose_name_plural": "Legal entities",
                "ordering": ["-is_active", "legal_name"],
                "indexes": [
                    models.Index(fields=["is_active"], name="legal_legal_is_acti_9e8bfc_idx"),
                    models.Index(fields=["country_code"], name="legal_legal_country_60a51b_idx"),
                ],
            },
        ),
    ]
