# Generated by Django 4.2.8 on 2026-02-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("legal", "0002_create_default_entity"),
    ]

    operations = [
        migrations.AddField(
            model_name="legalentity",
            name="legal_email",
            field=models.EmailField(
                blank=True,
                help_text="Official contact email for this legal entity",
                max_length=255,
                verbose_name="Legal email",
            ),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Main phone number for this legal entity",
                max_length=30,
                verbose_name="Phone",
            ),
        ),
    ]
