# Generated by Django 4.2.8 on 2025-12-16 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clinical", "0007_add_medical_fields_to_patient"),
    ]

    operations = [
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "encounter_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial Consultation"),
                            ("followup", "Follow-up"),
                            ("emergency", "Emergency"),
                            ("routine", "Routine Check-up"),
                        ],
                        default="routine",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("scheduled_at", models.DateTimeField(verbose_name="Scheduled At")),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Started At"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Completed At"),
                ),
                (
                    "subjective",
                    models.TextField(
                        blank=True,
                        help_text="Patient symptoms, concerns",
                        verbose_name="Subjective (S)",
                    ),
                ),
                (
                    "objective",
                    models.TextField(
                        blank=True,
                        help_text="Observations, measurements",
                        verbose_name="Objective (O)",
                    ),
                ),
                (
                    "assessment",
                    models.TextField(
                        blank=True,
                        help_text="Diagnosis, clinical impression",
                        verbose_name="Assessment (A)",
                    ),
                ),
                (
                    "plan",
                    models.TextField(
                        blank=True, help_text="Treatment plan, next steps", verbose_name="Plan (P)"
                    ),
                ),
                (
                    "chief_complaint",
                    models.CharField(blank=True, max_length=500, verbose_name="Chief Complaint"),
                ),
                ("diagnosis", models.TextField(blank=True, verbose_name="Diagnosis")),
                ("prescriptions", models.TextField(blank=True, verbose_name="Prescriptions")),
                ("notes", models.TextField(blank=True, verbose_name="Additional Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legacy_encounters",
                        to="clinical.patient",
                        verbose_name="Patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Encounter",
                "verbose_name_plural": "Encounters",
                "db_table": "encounters",
                "ordering": ["-scheduled_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "-scheduled_at"], name="encounters_patient_84256b_idx"
                    ),
                    models.Index(fields=["status"], name="encounters_status_2bbb51_idx"),
                    models.Index(fields=["-scheduled_at"], name="encounters_schedul_5f0cd5_idx"),
                ],
            },
        ),
    ]
