# Generated by Django 4.2.8 on 2025-12-22 13:57

import apps.encounters.models_media
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("encounters", "0001_update_patient_fk_to_clinical"),
    ]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="practitioner",
            field=models.ForeignKey(
                blank=True,
                help_text="Practitioner responsible for this encounter",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="encounters",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Practitioner",
            ),
        ),
        migrations.CreateModel(
            name="ClinicalMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("photo", "Photo")],
                        default="photo",
                        max_length=20,
                        verbose_name="Media Type",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("before", "Before Treatment"),
                            ("after", "After Treatment"),
                            ("progress", "Progress Photo"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Clinical category for this media",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        help_text="Clinical photo file",
                        upload_to=apps.encounters.models_media.clinical_media_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"],
                                message="Only JPEG, PNG, and WebP images are allowed",
                            )
                        ],
                        verbose_name="File",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Clinical notes about this media (optional)",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Soft delete timestamp for audit trail",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        help_text="Clinical encounter this media is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="encounters.encounter",
                        verbose_name="Encounter",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="Practitioner who uploaded this media",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_media",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinical Media",
                "verbose_name_plural": "Clinical Media",
                "db_table": "clinical_media",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["encounter", "-created_at"], name="clinical_me_encount_288770_idx"
                    ),
                    models.Index(
                        fields=["uploaded_by", "-created_at"], name="clinical_me_uploade_2861e3_idx"
                    ),
                    models.Index(fields=["deleted_at"], name="clinical_me_deleted_fc4a0d_idx"),
                ],
            },
        ),
    ]
