# Generated by Django 4.2.8 on 2025-12-30 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clinical", "0101_encounter_attachment_counters"),
        ("encounters", "0003_drop_legacy_encounters_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicalmedia",
            name="encounter",
            field=models.ForeignKey(
                help_text="Clinical encounter this media is associated with",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clinical_media",
                to="clinical.encounter",
                verbose_name="Encounter",
            ),
        ),
        migrations.DeleteModel(
            name="Encounter",
        ),
    ]
