# Generated by Django 4.2.8 on 2026-02-23 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0007_sale_legal_entity"),
        ("proposals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="accepted_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when proposal was accepted", null=True
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who accepted this proposal",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_proposals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="sent_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when proposal was sent to patient", null=True
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="valid_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Proposal expiration timestamp (created_at + 30 days by default)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="converted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when sale was created (same as accepted_at)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="converted_to_sale",
            field=models.ForeignKey(
                blank=True,
                help_text="Sale created from this proposal (null if not yet accepted)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_proposal",
                to="sales.sale",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("accepted", "Accepted"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="draft",
                help_text="Proposal status (draft/sent/accepted/cancelled/expired)",
                max_length=20,
            ),
        ),
    ]
