# Generated by Django 4.2.8 on 2026-02-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposals", "0003_migrate_statuses"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposalline",
            name="type",
            field=models.CharField(
                choices=[("per_session", "Per Session"), ("full_package", "Full Package")],
                default="per_session",
                help_text="Billing type: per_session (default) or full_package (creates TreatmentPlan)",
                max_length=20,
            ),
        ),
    ]
