# Generated by Django 4.2.8 on 2025-12-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sku", models.CharField(max_length=100, unique=True, verbose_name="SKU")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("category", models.CharField(blank=True, max_length=100, verbose_name="Category")),
                ("brand", models.CharField(blank=True, max_length=100, verbose_name="Brand")),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Price"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Cost"
                    ),
                ),
                ("stock_quantity", models.IntegerField(default=0, verbose_name="Stock Quantity")),
                (
                    "low_stock_threshold",
                    models.IntegerField(default=10, verbose_name="Low Stock Threshold"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "products",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["sku"], name="products_sku_fe2039_idx"),
                    models.Index(fields=["name"], name="products_name_6f9890_idx"),
                    models.Index(fields=["category"], name="products_categor_fce6e6_idx"),
                ],
            },
        ),
    ]
