"""
Update ClinicalPhoto index name to comply with 30 character limit.

Generated by Django 4.2.8 on 2025-12-15
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_layer2_a1_clinical_domain_integrity'),
    ]

    operations = [
        # Remove old index with long name (if it exists in DB)
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS idx_clinical_photo_patient_timeline;",
            reverse_sql="-- No reverse needed",
        ),
        # Add new index with shorter name
        migrations.AddIndex(
            model_name='clinicalphoto',
            index=models.Index(fields=['patient', '-created_at'], name='idx_clin_photo_timeline'),
        ),
    ]
