# Generated by Django 4.2.8 on 2025-12-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0005_fix_clinicalphoto_index_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['patient', '-created_at'], name='idx_encounter_patient_timeline'),
        ),
    ]
