# Generated by Django 4.2.8 on 2025-12-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinical", "0006_encounter_idx_encounter_patient_timeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="allergies",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="patient",
            name="blood_type",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="current_medications",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="patient",
            name="medical_history",
            field=models.TextField(blank=True, default=""),
        ),
    ]
