# Generated by Django 4.2.8 on 2025-12-16 21:11

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):
    dependencies = [
        ("clinical", "0007_add_medical_fields_to_patient"),
    ]

    operations = [
        # Enable pg_trgm extension for fuzzy text search
        TrigramExtension(),
    ]
