# Generated by Django 4.2.8 on 2025-12-16 21:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clinical", "0008_enable_trigram_extension"),
    ]

    operations = [
        # GIN trigram index for fuzzy full name search
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS idx_patient_fullname_trgm ON patient USING GIN (full_name_normalized gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS idx_patient_fullname_trgm;",
        ),
    ]
