# Generated by Django 4.2.8 on 2025-12-16 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clinical", "0009_add_patient_search_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientMergeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("merged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("phone_exact", "Phone Exact Match"),
                            ("email_exact", "Email Exact Match"),
                            ("name_trgm", "Name Trigram Similarity"),
                            ("manual", "Manual Merge"),
                            ("other", "Other"),
                        ],
                        default="manual",
                        help_text="How the duplicate was identified",
                        max_length=20,
                    ),
                ),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        help_text="Match evidence (sanitized): phone_masked, email_masked, similarity_score, etc.",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Free-text explanation of merge reason", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Merge Log",
                "verbose_name_plural": "Patient Merge Logs",
                "db_table": "patient_merge_log",
                "ordering": ["-merged_at"],
            },
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["is_merged"], name="idx_patient_merged"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["merged_into_patient"], name="idx_patient_merge_target"),
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.CheckConstraint(
                check=models.Q(("merged_into_patient", models.F("id")), _negated=True),
                name="patient_no_self_merge",
            ),
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("is_merged", False), ("merged_into_patient__isnull", False), _connector="OR"
                ),
                name="patient_merged_requires_target",
            ),
        ),
        migrations.AddField(
            model_name="patientmergelog",
            name="merged_by_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed the merge",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patient_merges_performed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="patientmergelog",
            name="source_patient",
            field=models.ForeignKey(
                help_text="Patient being merged (becomes inactive)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="merge_source_logs",
                to="clinical.patient",
            ),
        ),
        migrations.AddField(
            model_name="patientmergelog",
            name="target_patient",
            field=models.ForeignKey(
                help_text="Patient receiving merged data (remains active)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="merge_target_logs",
                to="clinical.patient",
            ),
        ),
        migrations.AddIndex(
            model_name="patientmergelog",
            index=models.Index(fields=["source_patient"], name="idx_merge_source"),
        ),
        migrations.AddIndex(
            model_name="patientmergelog",
            index=models.Index(fields=["target_patient"], name="idx_merge_target"),
        ),
        migrations.AddIndex(
            model_name="patientmergelog",
            index=models.Index(fields=["-merged_at"], name="idx_merge_date"),
        ),
    ]
