# Generated by Django 4.2.8 on 2025-12-22 10:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("clinical", "0010_add_patient_merge_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "default_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Default price in EUR (nullable for flexible pricing)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "requires_stock",
                    models.BooleanField(
                        default=False, help_text="If true, check stock availability before booking"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Treatment",
                "verbose_name_plural": "Treatments",
                "db_table": "treatment",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["is_active"], name="idx_treatment_active"),
                    models.Index(fields=["name"], name="idx_treatment_name"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EncounterTreatment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Overrides Treatment.default_price (nullable)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounter_treatments",
                        to="clinical.encounter",
                    ),
                ),
                (
                    "treatment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encounter_treatments",
                        to="clinical.treatment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Encounter Treatment",
                "verbose_name_plural": "Encounter Treatments",
                "db_table": "encounter_treatment",
                "indexes": [
                    models.Index(fields=["encounter"], name="idx_encounter_treatment_enc"),
                    models.Index(fields=["treatment"], name="idx_encounter_treatment_trt"),
                ],
                "unique_together": {("encounter", "treatment")},
            },
        ),
    ]
