# Generated by Django 4.2.8 on 2025-12-28 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authz", "0006_add_must_change_password_and_audit"),
        ("clinical", "0012_add_clinical_charge_proposal"),
    ]

    operations = [
        migrations.CreateModel(
            name="PractitionerBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("start", models.DateTimeField(help_text="Block start time (timezone-aware)")),
                ("end", models.DateTimeField(help_text="Block end time (timezone-aware)")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("vacation", "Vacation"),
                            ("blocked", "Blocked/Unavailable"),
                            ("personal", "Personal Time"),
                            ("training", "Training"),
                        ],
                        default="blocked",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='Display title (e.g., "Vacaciones", "No disponible")',
                        max_length=255,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_practitioner_blocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_blocks",
                        to="authz.practitioner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Practitioner Block",
                "verbose_name_plural": "Practitioner Blocks",
                "db_table": "practitioner_blocks",
                "ordering": ["start"],
                "indexes": [
                    models.Index(fields=["practitioner", "start"], name="idx_block_pract_start"),
                    models.Index(
                        fields=["practitioner", "is_deleted"], name="idx_block_pract_deleted"
                    ),
                    models.Index(fields=["start", "end"], name="idx_block_time_range"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="practitionerblock",
            constraint=models.CheckConstraint(
                check=models.Q(("end__gt", models.F("start"))), name="block_end_after_start"
            ),
        ),
    ]
