# Generated by Django 4.2.8 on 2025-12-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinical", "0013_practitionerblock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="document_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[("dni", "DNI/ID Card"), ("passport", "Passport"), ("other", "Other")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="nationality",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="privacy_policy_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patient",
            name="privacy_policy_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="terms_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patient",
            name="terms_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
