# Generated by Django 4.2.8 on 2026-01-04 21:45

import apps.clinical.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clinical", "0101_encounter_attachment_counters"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("photo", "Photo")],
                        default="photo",
                        max_length=20,
                        verbose_name="Media Type",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("before", "Before Treatment"),
                            ("after", "After Treatment"),
                            ("progress", "Progress Photo"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Clinical category for this media",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        help_text="Clinical photo file",
                        upload_to=apps.clinical.models.clinical_media_upload_path,
                        verbose_name="File",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Clinical notes about this media (optional)",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Soft delete timestamp for audit trail",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        help_text="Clinical encounter this media is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_media",
                        to="clinical.encounter",
                        verbose_name="Encounter",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="Practitioner who uploaded this media",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_media",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinical Media",
                "verbose_name_plural": "Clinical Media",
                "db_table": "clinical_media",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["encounter", "-created_at"], name="idx_cmedia_encounter"),
                    models.Index(fields=["uploaded_by", "-created_at"], name="idx_cmedia_uploader"),
                    models.Index(fields=["deleted_at"], name="idx_cmedia_deleted"),
                ],
            },
        ),
    ]
