# Generated by Django 4.2.8 on 2026-02-23 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("treatment_plans", "0001_initial"),
        ("clinical", "0103_move_proposals_to_own_app"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="treatment_plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Treatment plan this appointment belongs to (package sessions)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="treatment_plans.treatmentplan",
            ),
        ),
        migrations.AlterField(
            model_name="consent",
            name="consent_type",
            field=models.CharField(
                choices=[
                    ("privacy_policy", "Privacy Policy"),
                    ("terms_and_conditions", "Terms and Conditions"),
                    ("clinical_photos", "Clinical Photos"),
                    ("marketing_photos", "Marketing Photos"),
                    ("newsletter", "Newsletter"),
                    ("marketing_messages", "Marketing Messages"),
                ],
                max_length=30,
            ),
        ),
    ]
