# Generated by Django 4.2.8 on 2026-02-24 17:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("clinical", "0104_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientInsurance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider_name", models.CharField(max_length=255)),
                ("member_number", models.CharField(blank=True, max_length=255, null=True)),
                ("social_security_number", models.CharField(blank=True, max_length=255, null=True)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurances",
                        to="clinical.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Insurance",
                "verbose_name_plural": "Patient Insurances",
                "db_table": "patient_insurance",
                "ordering": ["-valid_from"],
                "indexes": [
                    models.Index(fields=["patient"], name="idx_insurance_patient"),
                    models.Index(fields=["is_active"], name="idx_insurance_active"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="patientinsurance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("patient",),
                name="unique_active_insurance_per_patient",
            ),
        ),
    ]
