# Generated by Django 4.2.8 on 2026-03-09 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("legal", "0004_fix_legacy_schema"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clinical", "0106_add_tenant_isolation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "action",
                    models.CharField(
                        help_text="Qualified action name, e.g. 'view_patient'.", max_length=40
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        help_text="Model / resource name, e.g. 'Patient', 'Encounter'.",
                        max_length=60,
                    ),
                ),
                (
                    "resource_id",
                    models.UUIDField(
                        blank=True,
                        help_text="PK of the accessed resource (if applicable).",
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Client IP address.", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="Client User-Agent header.", null=True),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        help_text="Tenant that owns this log entry.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinical_access_logs",
                        to="legal.legalentity",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Patient whose data was accessed (if applicable).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to="clinical.patient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed the action.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinical_access_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "clinical_access_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["legal_entity", "timestamp"], name="idx_access_log_le_ts")
                ],
            },
        ),
    ]
