# Generated by Django 4.2.8 on 2026-03-09 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clinical", "0107_clinical_access_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="treatment",
            field=models.ForeignKey(
                blank=True,
                help_text="Treatment expected for this appointment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="clinical.treatment",
            ),
        ),
        migrations.AddField(
            model_name="treatment",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=30, help_text="Standard duration of the treatment in minutes"
            ),
        ),
    ]
