# Generated by Django 4.2.8 on 2026-03-09 22:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("authz", "0008_add_legal_entity_constraint"),
        ("clinical", "0108_scheduling_phase1_treatment_duration_appointment_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="PractitionerTreatment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the practitioner currently performs this treatment",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "practitioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatment_capabilities",
                        to="authz.practitioner",
                    ),
                ),
                (
                    "treatment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practitioner_capabilities",
                        to="clinical.treatment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Practitioner Treatment Capability",
                "verbose_name_plural": "Practitioner Treatment Capabilities",
                "db_table": "practitioner_treatment",
                "indexes": [
                    models.Index(
                        fields=["practitioner", "is_active"], name="idx_pt_practitioner_active"
                    ),
                    models.Index(fields=["treatment", "is_active"], name="idx_pt_treatment_active"),
                ],
                "unique_together": {("practitioner", "treatment")},
            },
        ),
    ]
