# Generated by Django 4.2.8 on 2026-03-09 22:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_cliniclocation_tenant"),
        ("authz", "0009_drop_calendly_event_type_uris"),
        ("clinical", "0109_scheduling_phase2_practitioner_treatment"),
    ]

    operations = [
        migrations.CreateModel(
            name="PractitionerSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="Day of week (0=Monday … 6=Sunday)",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practitioner_schedules",
                        to="core.cliniclocation",
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="authz.practitioner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Practitioner Schedule",
                "verbose_name_plural": "Practitioner Schedules",
                "db_table": "practitioner_schedule",
                "indexes": [
                    models.Index(fields=["practitioner", "weekday"], name="idx_ps_pract_weekday"),
                    models.Index(fields=["clinic", "weekday"], name="idx_ps_clinic_weekday"),
                    models.Index(fields=["is_active"], name="idx_ps_active"),
                ],
                "unique_together": {("practitioner", "clinic", "weekday", "start_time")},
            },
        ),
    ]
