# Generated by Django 4.2.8 on 2026-03-15 15:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("authz", "0010_remove_practitioner_calendly_url"),
        ("core", "0002_cliniclocation_tenant"),
        ("legal", "0004_fix_legacy_schema"),
        ("clinical", "0113_appointment_soft_delete_complete"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("default_duration_minutes", models.PositiveIntegerField(default=30)),
                ("color", models.CharField(blank=True, default="#3B82F6", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Appointment Type",
                "verbose_name_plural": "Appointment Types",
                "db_table": "appointment_type",
            },
        ),
        migrations.RemoveIndex(
            model_name="appointment",
            name="idx_appointment_external_id",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="external_id",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="location",
        ),
        migrations.AddField(
            model_name="appointment",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="core.cliniclocation",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="duration_planned",
            field=models.PositiveIntegerField(default=30, help_text="Planned duration in minutes"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="duration_real",
            field=models.PositiveIntegerField(
                blank=True, help_text="Actual duration in minutes (filled on completion)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="practitioner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="authz.practitioner",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="source",
            field=models.CharField(
                choices=[("erp", "ERP"), ("public_api", "Public API"), ("manual", "Manual")],
                default="erp",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("confirmed", "Confirmed"),
                    ("checked_in", "Checked In"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No Show"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["clinic"], name="idx_appointment_clinic"),
        ),
        migrations.AddField(
            model_name="appointmenttype",
            name="legal_entity",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning legal entity (tenant isolation).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                to="legal.legalentity",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="appointment_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="clinical.appointmenttype",
            ),
        ),
        migrations.AddIndex(
            model_name="appointmenttype",
            index=models.Index(fields=["is_active"], name="idx_apt_type_active"),
        ),
        migrations.AddConstraint(
            model_name="appointmenttype",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "name"), name="unique_appointment_type_name_per_tenant"
            ),
        ),
    ]
