# Generated by Django 4.2.8 on 2026-03-15 22:49
"""
1. Drop rogue clinic_id column (wrong FK to legal_clinic, no data).
2. Rename Encounter.location → Encounter.clinic (safe RenameField).
"""
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clinical", "0114_appointmenttype_and_more"),
    ]

    operations = [
        # Drop rogue clinic_id that blocks the rename
        migrations.RunSQL(
            sql="ALTER TABLE encounter DROP COLUMN IF EXISTS clinic_id;",
            reverse_sql=(
                "ALTER TABLE encounter "
                "ADD COLUMN IF NOT EXISTS clinic_id uuid;"
            ),
        ),
        migrations.RenameField(
            model_name="encounter",
            old_name="location",
            new_name="clinic",
        ),
    ]
